# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'ExamplePickerTextField' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExamplePickerTextField
  pod 'PickerTextField', :path => '../../PickerTextField'

  target 'ExamplePickerTextFieldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExamplePickerTextFieldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
